# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# 
# More useless files lets go

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"