[tool.poetry]
name = "hwa"
version = "0.1.0"
description = ""
authors = ["Sophie Cheung <me@kcomain.dev>"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kcomain/hwa/issues"

[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.26.0"
aiohttp = {extras = ["async"], optional = true, version = "^3.7.4"}
smopy = {version = "^0.0.7", optional = true, extras = ["map"]}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-xprocess = "^0.18.1"
Sphinx = "^4.2.0"
sphinx-copybutton = "^0.4.0"
furo = "^2021.10.9"
sphinx-autobuild = "^2021.3.14"

[tool.poetry.extras]
map = ['smopy']
async = ['aiohttp']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
