pipeline:
    build:
        image: python:3.11
        commands:
            - pip3 install pipx
            - pipx install poetry
            - export PATH="/root/.local/bin:$PATH"
            - make
