pipeline:
    build:
        image: python
        commands:
            - pip3 install pipx
            - pipx install poetry
            - export PATH="/root/.local/bin:$PATH"
            - make dependencies
            # test stuff here

depends_on:
    - build
