pipeline:
    build:
        image: python
        commands:
            - pip3 install pipx
            - pipx install poetry
            - pipx ensurepath
            - make dependencies
            # test stuff here

depends_on:
    - build
